Install xz-utils in Gitlab CI.
Trying to fix this error:

  $ stack hpc report betty
  Downloading lts-10.3 build plan ...
  Downloaded lts-10.3 build plan.
  Preparing to install GHC to an isolated location.
  This will not interfere with any system-level installation.
  Preparing to download ghc-8.2.2 ...
  ghc-8.2.2: download has begun
  ghc-8.2.2:    9.61 MiB / 121.89 MiB (  7.88%) downloaded...
  [...]
  Downloaded ghc-8.2.2.
  The following executables are missing and must be installed: xz
  ERROR: Job failed: exit code 1